server:
    port: 8082
spring:
    data:
        cassandra:
            contact-points: cassandra.default.svc.cluster.local
            keyspace-name: mykeyspace
            schema-action: CREATE_IF_NOT_EXISTS
