server:
    port: 8082

---
spring:
    profiles:
        active: local
    data:
        cassandra:
            keyspace-name: mykeyspace
            schema-action: CREATE_IF_NOT_EXISTS
            contact-points: localhost

---

spring:
    profiles:
        active: kubernetes
    data:
        cassandra:
            contact-points: cassandra.default.svc.cluster.local
            keyspace-name: mykeyspace
            schema-action: CREATE_IF_NOT_EXISTS


